version: '2'
services:
  admin:
    image: dwi67/jboss-fuse-6.3-fabric
    ports:
      - "8181:8181"
      - "8101:8101"
    environment:
      - FUSE_KARAF_NAME=admin
      - FABRIC_USER=admin
      - FABRIC_PASSWD=admin
      - ZOOKEEPER_PASSWD=admin
      - SSH_PASSWD=admin
      - MANAGED_HOSTS=root1,root2,root3,root4
  root1:
    image: dwi67/jboss-fuse-6.3-ssh
    ports:
       - "9122:22"
       - "8191:8181"
       - "8111:8101"
  root2:
    image: dwi67/jboss-fuse-6.3-ssh
    ports:
       - "9222:22"
       - "8192:8181"
       - "8112:8101"
  root3:
    image: dwi67/jboss-fuse-6.3-ssh
    ports:
       - "9322:22"
       - "8193:8181"
       - "8113:8101"
  root4:
    image: dwi67/jboss-fuse-6.3-ssh
    ports:
       - "9422:22"
       - "8194:8181"
       - "8114:8101"
